spring:
  application:
    name: idf-outbound-connector-ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${azure.tenant-id}/v2.0
          secret-key: QzY1NEFEM0JDNkEzQjZDM0Y0NEVCNjE1QTU4Njg1NUI=


  datasource:
    url: jdbc:postgresql://coolify.ndashdigital.com:5432/postgres?currentSchema=identity_framework
    username: postgres
    password: KuLUmtOr2WPqdjUQ1DuRKnRdfrj61iaiS10maP42gAG40Uu07RwSSh2QXBWIS9gQ
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none       # change to update / validate / create-drop as needed
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

hr:
  default-department-name: UNKNOWN
  default-department-external-id: DEFAULT

azure:
  tenant-id: db067b07-979a-4dfa-8f65-2f7e2ed9201d
  client-id: 2fea369b-c5a4-40b3-8bbf-4634463719fd
  client-secret: 9sk8Q~Z66a0Z-jyQiaB0Z6wURBeMNkJLx5QMUarh
  graph:
    scope: https://graph.microsoft.com/.default

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
integrations:
  odoo:
    url: https://idsphere.odoo.com
    db: idsphere
    username: rico.brown@idsphere.net
    password: b85a1522e3ea70d0d7243d1945a3d39d73ced9b6
  jira:
    api-token: ATATT3xFfGF0BwmoolRove8ycD7uGLdjSVeo9chBNT8vl7gG9trUwLMDeI2WNqak-F7gXrtfixH3I6XcHbx8IngT2ziVtkJfgEyH3iDS-wfFXduHYdCKXr7b9CglP18338z0TV-ilUj70bv6HZ4wk69NfTXOyKqu8KFQUE4o8L6l9cRxxFptzkc=73EEC62E
    base-url: https://ndashprivatelimited.atlassian.net
    admin-email: ndashprivatelimited@gmail.com
  github:
    org: ${GITHUB_ORG:sdfsdf}
    token: ${GITHUB_TOKEN:5465465}
  workday:

scheduler:
  hr-sync:
    cron: 0 0 * * * *





