spring:
  application:
    name: idf-outbound-connector-ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${azure.tenant-id}/v2.0
          secret-key: QzY1NEFEM0JDNkEzQjZDM0Y0NEVCNjE1QTU4Njg1NUI=


  datasource:
    url: jdbc:postgresql://coolify.ndashdigital.com:5432/postgres?currentSchema=identity_framework
    username: postgres
    password: KuLUmtOr2WPqdjUQ1DuRKnRdfrj61iaiS10maP42gAG40Uu07RwSSh2QXBWIS9gQ
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none       # change to update / validate / create-drop as needed
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

azure:
  tenant-id: db067b07-979a-4dfa-8f65-2f7e2ed9201d
  client-id: 2fea369b-c5a4-40b3-8bbf-4634463719fd
  client-secret: SS28Q~Tjbcw1a.uBN_119o.uMt3-RxCU1y9wkawX
  graph:
    scope: https://graph.microsoft.com/.default

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
integrations:
  odoo:
    url: https://idsphere.odoo.com
    db: idsphere
    username: rico.brown@idsphere.net
    password: 30d67af5d9c185e36db036f310a2227105f12946
  jira:
    api-token: ATATT3xFfGF0oSFcRQ7o5Lhh8oQD1OUw1o0AyFTdHOBLP2nvGm4p08aeZVlrmaNMaCNxftzcJuPB2geOWkuyxI0YomPKuY-oRhyQq0Hq_cxKoqriaYacSZgMoxN6ubOE9BObVDZzszR5YeTuYSNS7ADVJN2cnDhlFDTuf2klgZDJJ9kNljcIOAY=AF29FD23
    base-url: https://ndashprivatelimited.atlassian.net
    admin-email: ndashprivatelimited@gmail.com
  github:
    org: Ndash-IDF
    token: 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
  workday:






